# Generated by Django 4.0.4 on 2022-10-02 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='team',
            name='designation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='team',
            name='facebook_link',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='google_plus_link',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='photo',
            field=models.ImageField(null=True, upload_to='Photos/%Y/%M/%D'),
        ),
        migrations.AddField(
            model_name='team',
            name='twitter_link',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
